//------------------------------------------------------------------------
// Copyright(c) 2026 .
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Zone.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Zone VST3 (64Bit)"
#else
#define stringFileDescription	"Zone VST3"
#endif
#define stringCompanyName		"\0"
#define stringLegalCopyright	"Copyright(c) 2026 ."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
